const PROJECTS={
  haproxy:{unit:'U5',title:'HAProxy Load Balancer',type:'NETWORK',intro:"Mise en place d'un système de répartition de charge avec HAProxy pour distribuer automatiquement le trafic web entre plusieurs serveurs Apache, avec gestion de la haute disponibilité et de la bascule en cas de panne.",objective:'Répartir les requêtes web entre plusieurs serveurs Apache afin d’éviter qu’un seul serveur ne porte toute la charge et de prévoir une continuité de service en cas de panne.',implementation:['Déploiement d’un frontal HAProxy dans l’architecture.','Configuration de plusieurs serveurs Apache comme serveurs de destination.','Mise en place des règles de répartition du trafic web.','Prise en compte de la disponibilité des serveurs et de la bascule en cas de panne.'],skills:['Configuration réseau','Haute disponibilité','Administration Linux','Services web','Diagnostic d’infrastructure'],tags:['HAProxy','Apache','Load Balancing','Linux'],report:'https://drive.google.com/file/d/1n8DX02oY0rDIyOPgySvF0YfUvFqK15Do/view?usp=sharing'},
  'dns-web':{unit:'U5',title:'DNS & Serveur Web',type:'SERVICES',intro:"Configuration d'un serveur DNS pour la résolution de noms et mise en place d'un serveur web Apache, avec zones DNS, enregistrements A/CNAME et hôtes virtuels.",objective:'Mettre en place les services nécessaires pour faire correspondre des noms à des ressources réseau et héberger plusieurs sites web sur une même infrastructure.',implementation:['Configuration du service DNS avec Bind9.','Gestion des zones DNS et des enregistrements A et CNAME.','Déploiement et configuration du serveur web Apache.','Mise en place des hôtes virtuels pour héberger plusieurs sites sur une même machine.'],skills:['Administration DNS','Bind9','Apache','Virtual Hosts','Services réseau'],tags:['DNS','Bind9','Apache','Virtual Hosts'],report:'https://drive.google.com/file/d/104UtphI2U6e0K4cUl6gnph_N-_2GIGjO/view?usp=sharing'},
  'linux-admin':{unit:'U6',title:'Administration Linux',type:'LINUX',intro:"Gestion des utilisateurs et groupes, permissions avancées, sécurisation de fichiers critiques et administration sudo avec journalisation des actions.",objective:'Administrer un système Linux en contrôlant les comptes, les groupes, les droits d’accès et les actions privilégiées.',implementation:['Création et gestion des utilisateurs et des groupes.','Configuration et étude des permissions avancées : SetUID, SetGID et Sticky Bit.','Sécurisation des fichiers critiques du système.','Administration des droits sudo et suivi des actions administratives.'],skills:['Linux Administration','Gestion des droits','Sécurité système','Sudo','Gestion utilisateurs / groupes'],tags:['Linux Admin','Permissions','SetUID / SetGID','Sticky Bit','Sudo','Security'],report:'https://drive.google.com/file/d/1mHuwza5Tt45IAQ2N1LNR1zX1cOhR7AwH/view?usp=sharing'},
  'infra-linux':{unit:'U6',title:'Infrastructure Linux',type:'INFRA',intro:"Déploiement et configuration d'une infrastructure Linux avec administration de serveurs, automatisation de tâches et scripts Bash.",objective:'Mettre en œuvre une infrastructure Linux et automatiser une partie des tâches d’administration afin de rendre les opérations plus structurées et reproductibles.',implementation:['Déploiement et configuration de serveurs Linux.','Administration des composants de l’infrastructure.','Création de scripts Bash pour automatiser des tâches récurrentes.','Organisation des opérations d’administration autour de l’infrastructure mise en place.'],skills:['Linux Server','Bash','Automatisation','Administration système','Infrastructure'],tags:['Linux Server','Bash','Automation','Infrastructure'],report:'https://drive.google.com/file/d/1zaINmaetE5_5Xmjx3zsarkIBUZYtAXJq/view?usp=sharing'},
  glpi:{unit:'U7',title:'Serveur GLPI',type:'ITSM',intro:"Déploiement d'une solution de gestion de parc permettant de centraliser l'inventaire matériel et logiciel et d'organiser le support technique via une plateforme Helpdesk.",objective:'Centraliser la connaissance du parc informatique et structurer le traitement des demandes de support grâce à une solution ITSM.',implementation:['Déploiement de la solution GLPI.','Centralisation des informations liées au matériel et aux logiciels.','Mise en place d’une logique d’inventaire du parc.','Organisation du support technique via la fonction Helpdesk.'],skills:['ITSM','Gestion de parc','Inventaire','Helpdesk','Support informatique'],tags:['GLPI','ITSM','Asset Management','Helpdesk','Inventory'],report:'https://docs.google.com/document/d/1yY2MmOR9ePiEnVVw-RkueW7k_6nNzBaA/edit?usp=sharing&ouid=113695881678060958123&rtpof=true&sd=true'},
  'active-directory':{unit:'U7',title:'Active Directory',type:'IDENTITY',intro:"Mise en place d'un service d'annuaire centralisé permettant de structurer les comptes, les accès et les configurations du parc via des stratégies de groupe (GPO).",objective:'Centraliser la gestion des identités et homogénéiser la configuration du parc informatique au travers d’un annuaire et de stratégies de groupe.',implementation:['Déploiement d’un environnement Windows Server avec Active Directory.','Organisation des comptes et des accès dans un annuaire centralisé.','Mise en place de stratégies de groupe (GPO).','Uniformisation de certaines configurations du parc grâce aux politiques appliquées.'],skills:['Windows Server','Active Directory','Gestion des identités','GPO','Administration réseau'],tags:['Windows Server','Active Directory','GPO','Identity'],report:'https://drive.google.com/file/d/1wd97bSoOJrvZuvqivmdq4ZoaJpDs4z6G/view?usp=sharing'}
};
const slug=location.pathname.split('/').pop().replace('.html','');
const p=PROJECTS[slug];
const set=(sel,val)=>{const e=document.querySelector(sel);if(e)e.textContent=val};
if(p){
 document.title=`${p.title} — Romain Barbière`;
 document.querySelectorAll('[data-unit]').forEach(e=>e.textContent=p.unit);
 set('[data-type]',p.type); set('[data-title]',p.title); set('[data-description]',p.intro); set('[data-objective]',p.objective); set('[data-stack]',p.tags.slice(0,3).join(' · '));
 const impl=document.querySelector('[data-implementation]'); if(impl) impl.innerHTML=p.implementation.map(x=>`<li>${x}</li>`).join('');
 const skills=document.querySelector('[data-skills]'); if(skills) skills.innerHTML=p.skills.map(x=>`<span>${x}</span>`).join('');
 const tags=document.querySelector('[data-tags]'); if(tags) tags.innerHTML=p.tags.map(x=>`<span>${x}</span>`).join('');
 document.querySelectorAll('[data-report]').forEach(report=>{ report.href=p.report; report.target='_blank'; report.rel='noopener noreferrer'; });
}
