const projectData=[
{title:'HAProxy Load Balancer',type:'NETWORK',description:"Mise en place d'un système de répartition de charge avec HAProxy pour distribuer automatiquement le trafic web entre plusieurs serveurs Apache, avec gestion de la haute disponibilité et de la bascule en cas de panne.",tags:['HAProxy','Apache','Load Balancing','Linux'],link:'https://drive.google.com/file/d/1orJqhTzWo4JJt-atZo68q7DtiWmaQ8fi/view?usp=drive_link'},
{title:'DNS & Serveur Web',type:'SERVICES',description:"Configuration d'un serveur DNS pour la résolution de noms et mise en place d'un serveur web Apache, avec zones DNS, enregistrements A/CNAME et hôtes virtuels.",tags:['DNS','Bind9','Apache','Virtual Hosts'],link:'https://drive.google.com/file/d/1g-LJXD5bluByPVxsv0EKLNxTXw20EdfM/view?usp=drive_link'},
{title:'Administration Linux',type:'LINUX',description:"Gestion des utilisateurs et groupes, permissions avancées, sécurisation de fichiers critiques et administration sudo avec journalisation des actions.",tags:['Linux Admin','Permissions','Sudo','Security'],link:'https://drive.google.com/file/d/16iajoQaNlVseb4Ib5dBC0HL9Tjr4eSQa/view?usp=drive_link'},
{title:'Infrastructure Linux',type:'INFRA',description:"Déploiement et configuration d'une infrastructure Linux avec administration de serveurs, automatisation de tâches et scripts Bash.",tags:['Linux Server','Bash','Automation','Infrastructure'],link:'https://drive.google.com/file/d/1b6HA--aYYhMlNDoBfLRvXhCRyt4dofwh/view?usp=drive_link'},
{title:'Serveur GLPI',type:'ITSM',description:"Déploiement d'une solution de gestion de parc permettant de centraliser l'inventaire matériel et logiciel et d'organiser le support technique via une plateforme Helpdesk.",tags:['GLPI','ITSM','Asset Management','Helpdesk'],link:'https://docs.google.com/document/d/1jUZxO36raOoGqUDvRdQHIABXzx9jBAA2/edit?usp=drive_link&ouid=113695881678060958123&rtpof=true&sd=true'},
{title:'Active Directory',type:'IDENTITY',description:"Mise en place d'un service d'annuaire centralisé permettant de structurer les comptes, les accès et les configurations du parc via des stratégies de groupe (GPO).",tags:['Windows Server','Active Directory','GPO','Identity'],link:'https://drive.google.com/file/d/1elvZpKq5xmvcdeelqnD0ypMBVhBlw6pe/view?usp=drive_link'}
];
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
class Portfolio{
constructor(){this.loading=$('#loading-screen');this.bar=$('.loading-bar');this.percent=$('.loading-percentage');this.status=$('.loading-status');this.main=$('#main-app');this.projects=$('#projects-overlay');this.modal=$('#project-modal-content');this.terminal=$('#terminal-overlay');this.input=$('#terminal-input');this.init()}
init(){this.boot();this.nav();this.projectsUI();this.terminalUI();this.scrollReveal();this.progress();this.parallax();}
boot(){
 const command=$('#boot-command-text'),lines=$$('.terminal-line',this.loading),state=$('#radar-state'),core=$('.cinematic-core'),radar=$('.dragon-radar',this.loading),point=$('.scanner-point',this.loading),caption=$('#scouter-caption'),sub=$('#scouter-sub'),found=$('#found-message'),connect=$('#connect-message');
 let p=0;
 const typeCommand=(text,speed=18)=>{command.textContent='';let i=0;const timer=setInterval(()=>{command.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(timer)},speed)};
 const positions=[[22,30],[63,24],[74,54],[55,72],[31,64],[78,35],[45,43]];
 const movePoint=(x,y)=>{point.style.left=x+'%';point.style.top=y+'%'};
 typeCommand('POWER ON // PERSONAL SCOUT');
 state.textContent='RECHERCHE'; caption.textContent='RECHERCHE...'; sub.textContent='CIBLE NON IDENTIFIÉE'; core?.classList.add('radar-searching');
 movePoint(48,48);
 let pos=0;
 setTimeout(()=>{typeCommand('SCANNING // LOOKING FOR SIGNAL');lines[0]?.classList.add('active');},450);
 const searchTimer=setInterval(()=>{const [x,y]=positions[pos++%positions.length];movePoint(x,y)},520);
 setTimeout(()=>{clearInterval(searchTimer);movePoint(66,31);core?.classList.add('radar-found');state.textContent='CIBLE TROUVÉE';caption.textContent='SIGNAL DÉTECTÉ';sub.textContent='ANALYSE EN COURS';typeCommand('SIGNAL DETECTED // ANALYZING');lines[1]?.classList.add('active');point?.classList.add('locked');},3650);
 setTimeout(()=>{core?.classList.remove('radar-searching');core?.classList.add('radar-analyzing');state.textContent='ANALYSE';caption.textContent='ANALYSE DU SIGNAL';sub.textContent='RB // PERSONAL NODE';typeCommand('ANALYZING SIGNATURE // RB');lines[1]?.classList.add('done');lines[2]?.classList.add('active');},4050);
 setTimeout(()=>{found?.classList.add('visible');state.textContent='PORTFOLIO TROUVÉ';caption.textContent='RB';sub.textContent='PERSONAL PORTFOLIO';typeCommand('MATCH CONFIRMED // PORTFOLIO FOUND');lines[2]?.classList.add('done');lines[3]?.classList.add('active');},4700);
 setTimeout(()=>{connect.textContent='CONNEXION AU PORTFOLIO...';typeCommand('ESTABLISHING SECURE CONNECTION');this.status.textContent='PORTFOLIO FOUND';state.textContent='CONNEXION';},5250);
 const interval=setInterval(()=>{const boost=p<72?4.6:2.8;p=Math.min(100,p+boost+Math.random()*1.4);this.bar.style.width=p+'%';this.percent.textContent=Math.floor(p)+'%';},100);
 setTimeout(()=>{clearInterval(interval);p=100;this.bar.style.width='100%';this.percent.textContent='100%';lines.forEach(line=>line.classList.add('active','done'));this.status.textContent='CONNEXION ÉTABLIE';state.textContent='ONLINE';connect.textContent='CONNEXION ÉTABLIE';typeCommand('WELCOME // ROMAIN BARBIÈRE');setTimeout(()=>{this.loading.classList.add('unlock');this.loading.querySelector('.cinematic-boot')?.classList.add('unlocking');setTimeout(()=>{this.loading.classList.remove('active','unlock');this.main.classList.add('visible')},760)},900)},6250);
}

nav(){const links=$$('.quick-nav a');const ids=['profil','experience','veille','projets','contact'];const update=()=>{let current='';const y=scrollY+innerHeight*.3;ids.forEach(id=>{const s=document.getElementById(id);if(s&&s.offsetTop<=y)current=id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))};addEventListener('scroll',update,{passive:true});update()}
projectsUI(){ $$('.project-card').forEach(c=>c.addEventListener('click',()=>this.openProject(+c.dataset.project))); $('#projects-trigger')?.addEventListener('click',()=>this.openProject(0)); $('#close-projects')?.addEventListener('click',()=>this.close(this.projects)); this.projects.addEventListener('click',e=>{if(e.target===this.projects||e.target.classList.contains('overlay-background'))this.close(this.projects)})}
openProject(i){const p=projectData[i];if(!p)return;this.modal.innerHTML=`<article class="modal-card"><span class="section-eyebrow">${String(i+1).padStart(2,'0')} · ${p.type}</span><h3>${p.title}</h3><p>${p.description}</p><div class="modal-tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="modal-footer"><small>Projet issu du parcours BTS SIO / SISR</small><a class="cta-button primary" href="${p.link}" target="_blank" rel="noopener noreferrer">Consulter le document ↗</a></div></article>`;this.open(this.projects)}
terminalUI(){const open=()=>{this.open(this.terminal);setTimeout(()=>this.input?.focus(),100)};$('#terminal-trigger')?.addEventListener('click',open);$('#hero-terminal')?.addEventListener('click',open);$('#close-terminal')?.addEventListener('click',()=>this.close(this.terminal));this.terminal.addEventListener('click',e=>{if(e.target===this.terminal)this.close(this.terminal)});this.input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const value=e.target.value.trim().toLowerCase();const body=$('#terminal-body');const line=document.createElement('p');line.innerHTML=`<span class="console-green">system@rb:~$</span> ${this.escape(e.target.value)}`;body.insertBefore(line,$('.terminal-command'));e.target.value='';if(value==='clear'){body.innerHTML='<div class="terminal-command"><span class="console-green">system@rb:~$</span><input id="terminal-input" autocomplete="off" spellcheck="false"></div>';this.input=$('#terminal-input');this.input.focus();return}const out=document.createElement('p');if(['projects','projets'].includes(value)){out.textContent='→ ouverture de la grille projets.';document.getElementById('projets').scrollIntoView({behavior:'smooth'});this.close(this.terminal)}else if(value==='experience'){out.textContent='→ parcours: 05.2022 / 01.2023 / 07.2025 / 09.2025 → aujourd’hui.';document.getElementById('experience').scrollIntoView({behavior:'smooth'});this.close(this.terminal)}else if(value==='veille'){out.textContent='→ radar actif: SASE / Zero Trust · IA réseau · post-quantique.';document.getElementById('veille').scrollIntoView({behavior:'smooth'});this.close(this.terminal)}else if(value==='contact'){out.textContent='→ romain.barbiere77@gmail.com'}else out.textContent='Commande inconnue. Essayez: projects, experience, veille, contact, clear.';body.insertBefore(out,$('.terminal-command'))})}
open(el){el.classList.add('active');el.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')};close(el){el.classList.remove('active');el.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
scrollReveal(){const items=$$('.glass-card,.project-card,.watch-card,.timeline-item');const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');obs.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'});items.forEach((el,i)=>{el.style.animationDelay=Math.min(i*55,450)+'ms';obs.observe(el)})}
progress(){const bar=$('#scroll-progress');const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max>0?scrollY/max*100:0)+'%'};addEventListener('scroll',update,{passive:true});update()}
parallax(){
 const scene=$('.hero-scene'); if(!scene)return;
 addEventListener('mousemove',e=>{const x=(innerWidth/2-e.clientX)/50,y=(innerHeight/2-e.clientY)/60;scene.style.transform=`translate3d(${x}px,${y}px,0)`;$$('.glass-card,.project-card,.watch-card').forEach(card=>{const r=card.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0){card.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);card.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`)}})},{passive:true});
}
escape(t){return t.replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}}
document.addEventListener('DOMContentLoaded',()=>new Portfolio());
document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.projects-overlay.active,.terminal-overlay.active').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-hidden','true')})});
